// flow-typed signature: 8157be44b05a104c326d964ee01ac572
// flow-typed version: <<STUB>>/pdfjs-dist_v^2.4.456/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pdfjs-dist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pdfjs-dist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pdfjs-dist/build/pdf' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/build/pdf.min' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/build/pdf.worker.entry' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/build/pdf.worker' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/build/pdf.worker.min' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/es5/build/pdf' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/es5/build/pdf.worker.entry' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/es5/build/pdf.worker' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/es5/web/pdf_viewer' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/image_decoders/pdf.image_decoders' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/image_decoders/pdf.image_decoders.min' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/annotation' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/arithmetic_decoder' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/bidi' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/ccitt_stream' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/ccitt' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/cff_parser' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/charsets' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/chunked_stream' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/cmap' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/colorspace' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/core_utils' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/crypto' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/document' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/encodings' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/evaluator' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/font_renderer' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/fonts' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/function' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/glyphlist' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/image_utils' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/image' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/jbig2_stream' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/jbig2' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/jpeg_stream' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/jpg' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/jpx_stream' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/jpx' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/metrics' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/murmurhash3' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/obj' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/operator_list' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/parser' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/pattern' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/pdf_manager' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/primitives' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/ps_parser' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/standard_fonts' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/stream' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/type1_parser' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/unicode' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/worker_stream' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/core/worker' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/annotation_layer' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/api_compatibility' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/api' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/canvas' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/content_disposition' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/display_utils' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/fetch_stream' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/font_loader' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/metadata' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/network_utils' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/network' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/node_stream' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/pattern_helper' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/svg' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/text_layer' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/transport_stream' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/webgl' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/worker_options' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/display/xml_parser' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/examples/node/domstubs' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/pdf' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/pdf.worker' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/shared/compatibility' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/shared/is_node' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/shared/message_handler' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/shared/util' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/annotation_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/api_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/bidi_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/cff_parser_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/clitests_helper' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/cmap_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/colorspace_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/core_utils_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/crypto_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/custom_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/display_svg_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/display_utils_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/document_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/encodings_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/evaluator_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/fetch_stream_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/function_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/jasmine-boot' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/message_handler_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/metadata_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/murmurhash3_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/network_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/network_utils_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/node_stream_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/parser_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/pdf_find_controller_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/pdf_find_utils_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/pdf_history_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/primitives_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/stream_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/test_utils' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/testreporter' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/type1_parser_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/ui_utils_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/unicode_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/test/unit/util_spec' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/annotation_layer_builder' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/app_options' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/app' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/base_viewer' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/chromecom' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/debugger' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/download_manager' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/firefox_print_service' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/firefoxcom' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/genericcom' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/genericl10n' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/grab_to_pan' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/interfaces' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/overlay_manager' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/password_prompt' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_attachment_viewer' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_cursor_tools' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_document_properties' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_find_bar' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_find_controller' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_find_utils' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_history' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_link_service' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_outline_viewer' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_page_view' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_presentation_mode' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_print_service' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_rendering_queue' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_sidebar_resizer' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_sidebar' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_single_page_viewer' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_thumbnail_view' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_thumbnail_viewer' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_viewer.component' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/pdf_viewer' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/preferences' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/secondary_toolbar' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/text_layer_builder' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/toolbar' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/ui_utils' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/view_history' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/lib/web/viewer_compatibility' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/web/pdf_viewer' {
  declare module.exports: any;
}

declare module 'pdfjs-dist/webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pdfjs-dist/build/pdf.js' {
  declare module.exports: $Exports<'pdfjs-dist/build/pdf'>;
}
declare module 'pdfjs-dist/build/pdf.min.js' {
  declare module.exports: $Exports<'pdfjs-dist/build/pdf.min'>;
}
declare module 'pdfjs-dist/build/pdf.worker.entry.js' {
  declare module.exports: $Exports<'pdfjs-dist/build/pdf.worker.entry'>;
}
declare module 'pdfjs-dist/build/pdf.worker.js' {
  declare module.exports: $Exports<'pdfjs-dist/build/pdf.worker'>;
}
declare module 'pdfjs-dist/build/pdf.worker.min.js' {
  declare module.exports: $Exports<'pdfjs-dist/build/pdf.worker.min'>;
}
declare module 'pdfjs-dist/es5/build/pdf.js' {
  declare module.exports: $Exports<'pdfjs-dist/es5/build/pdf'>;
}
declare module 'pdfjs-dist/es5/build/pdf.worker.entry.js' {
  declare module.exports: $Exports<'pdfjs-dist/es5/build/pdf.worker.entry'>;
}
declare module 'pdfjs-dist/es5/build/pdf.worker.js' {
  declare module.exports: $Exports<'pdfjs-dist/es5/build/pdf.worker'>;
}
declare module 'pdfjs-dist/es5/web/pdf_viewer.js' {
  declare module.exports: $Exports<'pdfjs-dist/es5/web/pdf_viewer'>;
}
declare module 'pdfjs-dist/image_decoders/pdf.image_decoders.js' {
  declare module.exports: $Exports<'pdfjs-dist/image_decoders/pdf.image_decoders'>;
}
declare module 'pdfjs-dist/image_decoders/pdf.image_decoders.min.js' {
  declare module.exports: $Exports<'pdfjs-dist/image_decoders/pdf.image_decoders.min'>;
}
declare module 'pdfjs-dist/lib/core/annotation.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/annotation'>;
}
declare module 'pdfjs-dist/lib/core/arithmetic_decoder.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/arithmetic_decoder'>;
}
declare module 'pdfjs-dist/lib/core/bidi.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/bidi'>;
}
declare module 'pdfjs-dist/lib/core/ccitt_stream.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/ccitt_stream'>;
}
declare module 'pdfjs-dist/lib/core/ccitt.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/ccitt'>;
}
declare module 'pdfjs-dist/lib/core/cff_parser.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/cff_parser'>;
}
declare module 'pdfjs-dist/lib/core/charsets.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/charsets'>;
}
declare module 'pdfjs-dist/lib/core/chunked_stream.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/chunked_stream'>;
}
declare module 'pdfjs-dist/lib/core/cmap.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/cmap'>;
}
declare module 'pdfjs-dist/lib/core/colorspace.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/colorspace'>;
}
declare module 'pdfjs-dist/lib/core/core_utils.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/core_utils'>;
}
declare module 'pdfjs-dist/lib/core/crypto.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/crypto'>;
}
declare module 'pdfjs-dist/lib/core/document.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/document'>;
}
declare module 'pdfjs-dist/lib/core/encodings.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/encodings'>;
}
declare module 'pdfjs-dist/lib/core/evaluator.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/evaluator'>;
}
declare module 'pdfjs-dist/lib/core/font_renderer.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/font_renderer'>;
}
declare module 'pdfjs-dist/lib/core/fonts.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/fonts'>;
}
declare module 'pdfjs-dist/lib/core/function.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/function'>;
}
declare module 'pdfjs-dist/lib/core/glyphlist.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/glyphlist'>;
}
declare module 'pdfjs-dist/lib/core/image_utils.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/image_utils'>;
}
declare module 'pdfjs-dist/lib/core/image.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/image'>;
}
declare module 'pdfjs-dist/lib/core/jbig2_stream.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/jbig2_stream'>;
}
declare module 'pdfjs-dist/lib/core/jbig2.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/jbig2'>;
}
declare module 'pdfjs-dist/lib/core/jpeg_stream.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/jpeg_stream'>;
}
declare module 'pdfjs-dist/lib/core/jpg.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/jpg'>;
}
declare module 'pdfjs-dist/lib/core/jpx_stream.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/jpx_stream'>;
}
declare module 'pdfjs-dist/lib/core/jpx.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/jpx'>;
}
declare module 'pdfjs-dist/lib/core/metrics.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/metrics'>;
}
declare module 'pdfjs-dist/lib/core/murmurhash3.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/murmurhash3'>;
}
declare module 'pdfjs-dist/lib/core/obj.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/obj'>;
}
declare module 'pdfjs-dist/lib/core/operator_list.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/operator_list'>;
}
declare module 'pdfjs-dist/lib/core/parser.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/parser'>;
}
declare module 'pdfjs-dist/lib/core/pattern.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/pattern'>;
}
declare module 'pdfjs-dist/lib/core/pdf_manager.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/pdf_manager'>;
}
declare module 'pdfjs-dist/lib/core/primitives.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/primitives'>;
}
declare module 'pdfjs-dist/lib/core/ps_parser.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/ps_parser'>;
}
declare module 'pdfjs-dist/lib/core/standard_fonts.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/standard_fonts'>;
}
declare module 'pdfjs-dist/lib/core/stream.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/stream'>;
}
declare module 'pdfjs-dist/lib/core/type1_parser.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/type1_parser'>;
}
declare module 'pdfjs-dist/lib/core/unicode.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/unicode'>;
}
declare module 'pdfjs-dist/lib/core/worker_stream.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/worker_stream'>;
}
declare module 'pdfjs-dist/lib/core/worker.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/core/worker'>;
}
declare module 'pdfjs-dist/lib/display/annotation_layer.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/annotation_layer'>;
}
declare module 'pdfjs-dist/lib/display/api_compatibility.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/api_compatibility'>;
}
declare module 'pdfjs-dist/lib/display/api.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/api'>;
}
declare module 'pdfjs-dist/lib/display/canvas.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/canvas'>;
}
declare module 'pdfjs-dist/lib/display/content_disposition.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/content_disposition'>;
}
declare module 'pdfjs-dist/lib/display/display_utils.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/display_utils'>;
}
declare module 'pdfjs-dist/lib/display/fetch_stream.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/fetch_stream'>;
}
declare module 'pdfjs-dist/lib/display/font_loader.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/font_loader'>;
}
declare module 'pdfjs-dist/lib/display/metadata.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/metadata'>;
}
declare module 'pdfjs-dist/lib/display/network_utils.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/network_utils'>;
}
declare module 'pdfjs-dist/lib/display/network.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/network'>;
}
declare module 'pdfjs-dist/lib/display/node_stream.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/node_stream'>;
}
declare module 'pdfjs-dist/lib/display/pattern_helper.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/pattern_helper'>;
}
declare module 'pdfjs-dist/lib/display/svg.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/svg'>;
}
declare module 'pdfjs-dist/lib/display/text_layer.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/text_layer'>;
}
declare module 'pdfjs-dist/lib/display/transport_stream.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/transport_stream'>;
}
declare module 'pdfjs-dist/lib/display/webgl.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/webgl'>;
}
declare module 'pdfjs-dist/lib/display/worker_options.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/worker_options'>;
}
declare module 'pdfjs-dist/lib/display/xml_parser.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/display/xml_parser'>;
}
declare module 'pdfjs-dist/lib/examples/node/domstubs.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/examples/node/domstubs'>;
}
declare module 'pdfjs-dist/lib/pdf.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/pdf'>;
}
declare module 'pdfjs-dist/lib/pdf.worker.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/pdf.worker'>;
}
declare module 'pdfjs-dist/lib/shared/compatibility.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/shared/compatibility'>;
}
declare module 'pdfjs-dist/lib/shared/is_node.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/shared/is_node'>;
}
declare module 'pdfjs-dist/lib/shared/message_handler.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/shared/message_handler'>;
}
declare module 'pdfjs-dist/lib/shared/util.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/shared/util'>;
}
declare module 'pdfjs-dist/lib/test/unit/annotation_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/annotation_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/api_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/api_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/bidi_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/bidi_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/cff_parser_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/cff_parser_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/clitests_helper.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/clitests_helper'>;
}
declare module 'pdfjs-dist/lib/test/unit/cmap_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/cmap_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/colorspace_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/colorspace_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/core_utils_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/core_utils_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/crypto_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/crypto_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/custom_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/custom_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/display_svg_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/display_svg_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/display_utils_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/display_utils_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/document_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/document_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/encodings_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/encodings_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/evaluator_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/evaluator_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/fetch_stream_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/fetch_stream_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/function_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/function_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/jasmine-boot.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/jasmine-boot'>;
}
declare module 'pdfjs-dist/lib/test/unit/message_handler_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/message_handler_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/metadata_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/metadata_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/murmurhash3_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/murmurhash3_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/network_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/network_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/network_utils_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/network_utils_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/node_stream_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/node_stream_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/parser_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/parser_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/pdf_find_controller_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/pdf_find_controller_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/pdf_find_utils_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/pdf_find_utils_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/pdf_history_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/pdf_history_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/primitives_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/primitives_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/stream_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/stream_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/test_utils.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/test_utils'>;
}
declare module 'pdfjs-dist/lib/test/unit/testreporter.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/testreporter'>;
}
declare module 'pdfjs-dist/lib/test/unit/type1_parser_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/type1_parser_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/ui_utils_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/ui_utils_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/unicode_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/unicode_spec'>;
}
declare module 'pdfjs-dist/lib/test/unit/util_spec.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/test/unit/util_spec'>;
}
declare module 'pdfjs-dist/lib/web/annotation_layer_builder.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/annotation_layer_builder'>;
}
declare module 'pdfjs-dist/lib/web/app_options.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/app_options'>;
}
declare module 'pdfjs-dist/lib/web/app.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/app'>;
}
declare module 'pdfjs-dist/lib/web/base_viewer.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/base_viewer'>;
}
declare module 'pdfjs-dist/lib/web/chromecom.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/chromecom'>;
}
declare module 'pdfjs-dist/lib/web/debugger.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/debugger'>;
}
declare module 'pdfjs-dist/lib/web/download_manager.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/download_manager'>;
}
declare module 'pdfjs-dist/lib/web/firefox_print_service.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/firefox_print_service'>;
}
declare module 'pdfjs-dist/lib/web/firefoxcom.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/firefoxcom'>;
}
declare module 'pdfjs-dist/lib/web/genericcom.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/genericcom'>;
}
declare module 'pdfjs-dist/lib/web/genericl10n.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/genericl10n'>;
}
declare module 'pdfjs-dist/lib/web/grab_to_pan.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/grab_to_pan'>;
}
declare module 'pdfjs-dist/lib/web/interfaces.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/interfaces'>;
}
declare module 'pdfjs-dist/lib/web/overlay_manager.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/overlay_manager'>;
}
declare module 'pdfjs-dist/lib/web/password_prompt.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/password_prompt'>;
}
declare module 'pdfjs-dist/lib/web/pdf_attachment_viewer.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_attachment_viewer'>;
}
declare module 'pdfjs-dist/lib/web/pdf_cursor_tools.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_cursor_tools'>;
}
declare module 'pdfjs-dist/lib/web/pdf_document_properties.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_document_properties'>;
}
declare module 'pdfjs-dist/lib/web/pdf_find_bar.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_find_bar'>;
}
declare module 'pdfjs-dist/lib/web/pdf_find_controller.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_find_controller'>;
}
declare module 'pdfjs-dist/lib/web/pdf_find_utils.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_find_utils'>;
}
declare module 'pdfjs-dist/lib/web/pdf_history.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_history'>;
}
declare module 'pdfjs-dist/lib/web/pdf_link_service.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_link_service'>;
}
declare module 'pdfjs-dist/lib/web/pdf_outline_viewer.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_outline_viewer'>;
}
declare module 'pdfjs-dist/lib/web/pdf_page_view.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_page_view'>;
}
declare module 'pdfjs-dist/lib/web/pdf_presentation_mode.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_presentation_mode'>;
}
declare module 'pdfjs-dist/lib/web/pdf_print_service.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_print_service'>;
}
declare module 'pdfjs-dist/lib/web/pdf_rendering_queue.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_rendering_queue'>;
}
declare module 'pdfjs-dist/lib/web/pdf_sidebar_resizer.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_sidebar_resizer'>;
}
declare module 'pdfjs-dist/lib/web/pdf_sidebar.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_sidebar'>;
}
declare module 'pdfjs-dist/lib/web/pdf_single_page_viewer.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_single_page_viewer'>;
}
declare module 'pdfjs-dist/lib/web/pdf_thumbnail_view.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_thumbnail_view'>;
}
declare module 'pdfjs-dist/lib/web/pdf_thumbnail_viewer.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_thumbnail_viewer'>;
}
declare module 'pdfjs-dist/lib/web/pdf_viewer.component.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_viewer.component'>;
}
declare module 'pdfjs-dist/lib/web/pdf_viewer.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/pdf_viewer'>;
}
declare module 'pdfjs-dist/lib/web/preferences.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/preferences'>;
}
declare module 'pdfjs-dist/lib/web/secondary_toolbar.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/secondary_toolbar'>;
}
declare module 'pdfjs-dist/lib/web/text_layer_builder.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/text_layer_builder'>;
}
declare module 'pdfjs-dist/lib/web/toolbar.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/toolbar'>;
}
declare module 'pdfjs-dist/lib/web/ui_utils.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/ui_utils'>;
}
declare module 'pdfjs-dist/lib/web/view_history.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/view_history'>;
}
declare module 'pdfjs-dist/lib/web/viewer_compatibility.js' {
  declare module.exports: $Exports<'pdfjs-dist/lib/web/viewer_compatibility'>;
}
declare module 'pdfjs-dist/web/pdf_viewer.js' {
  declare module.exports: $Exports<'pdfjs-dist/web/pdf_viewer'>;
}
declare module 'pdfjs-dist/webpack.js' {
  declare module.exports: $Exports<'pdfjs-dist/webpack'>;
}
