// flow-typed signature: 30def080d492d4696d2b0a2789d12e9a
// flow-typed version: <<STUB>>/react-pointable_v^1.1.1/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-pointable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-pointable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-pointable/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-pointable/lib/index' {
  declare module.exports: $Exports<'react-pointable/lib'>;
}
declare module 'react-pointable/lib/index.js' {
  declare module.exports: $Exports<'react-pointable/lib'>;
}
