// flow-typed signature: b69523646bb552950cb1a9ff60586458
// flow-typed version: <<STUB>>/react-pdf-highlighter_v^3.2.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-pdf-highlighter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-pdf-highlighter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-pdf-highlighter/flow-typed/npm/lodash.debounce_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/flow-typed/npm/pdfjs-dist_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/flow-typed/npm/react-dom_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/flow-typed/npm/react-pointable_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/components/AreaHighlight' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/components/Highlight' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/components/MouseMonitor' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/components/MouseSelection' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/components/PdfHighlighter' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/components/PdfLoader' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/components/Popup' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/components/Tip' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/components/TipContainer' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/lib/coordinates' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/lib/get-area-as-png' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/lib/get-bounding-rect' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/lib/get-client-rects' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/lib/optimize-client-rects' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/lib/pdfjs-dom' {
  declare module.exports: any;
}

declare module 'react-pdf-highlighter/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-pdf-highlighter/flow-typed/npm/lodash.debounce_vx.x.x.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/flow-typed/npm/lodash.debounce_vx.x.x'>;
}
declare module 'react-pdf-highlighter/flow-typed/npm/pdfjs-dist_vx.x.x.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/flow-typed/npm/pdfjs-dist_vx.x.x'>;
}
declare module 'react-pdf-highlighter/flow-typed/npm/react-dom_vx.x.x.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/flow-typed/npm/react-dom_vx.x.x'>;
}
declare module 'react-pdf-highlighter/flow-typed/npm/react-pointable_vx.x.x.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/flow-typed/npm/react-pointable_vx.x.x'>;
}
declare module 'react-pdf-highlighter/src/components/AreaHighlight.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/components/AreaHighlight'>;
}
declare module 'react-pdf-highlighter/src/components/Highlight.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/components/Highlight'>;
}
declare module 'react-pdf-highlighter/src/components/MouseMonitor.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/components/MouseMonitor'>;
}
declare module 'react-pdf-highlighter/src/components/MouseSelection.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/components/MouseSelection'>;
}
declare module 'react-pdf-highlighter/src/components/PdfHighlighter.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/components/PdfHighlighter'>;
}
declare module 'react-pdf-highlighter/src/components/PdfLoader.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/components/PdfLoader'>;
}
declare module 'react-pdf-highlighter/src/components/Popup.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/components/Popup'>;
}
declare module 'react-pdf-highlighter/src/components/Tip.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/components/Tip'>;
}
declare module 'react-pdf-highlighter/src/components/TipContainer.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/components/TipContainer'>;
}
declare module 'react-pdf-highlighter/src/index' {
  declare module.exports: $Exports<'react-pdf-highlighter/src'>;
}
declare module 'react-pdf-highlighter/src/index.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src'>;
}
declare module 'react-pdf-highlighter/src/lib/coordinates.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/lib/coordinates'>;
}
declare module 'react-pdf-highlighter/src/lib/get-area-as-png.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/lib/get-area-as-png'>;
}
declare module 'react-pdf-highlighter/src/lib/get-bounding-rect.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/lib/get-bounding-rect'>;
}
declare module 'react-pdf-highlighter/src/lib/get-client-rects.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/lib/get-client-rects'>;
}
declare module 'react-pdf-highlighter/src/lib/optimize-client-rects.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/lib/optimize-client-rects'>;
}
declare module 'react-pdf-highlighter/src/lib/pdfjs-dom.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/lib/pdfjs-dom'>;
}
declare module 'react-pdf-highlighter/src/types.js' {
  declare module.exports: $Exports<'react-pdf-highlighter/src/types'>;
}
