// flow-typed signature: 209ea96f86ee0033d2778f8e75286b1e
// flow-typed version: <<STUB>>/@jagatmachines/react-pdf-highlighter_v^3.3.0-alpha-03/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jagatmachines/react-pdf-highlighter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jagatmachines/react-pdf-highlighter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jagatmachines/react-pdf-highlighter/build/components/AreaHighlight' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/components/ContextMenu' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/components/Highlight' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/components/MouseMonitor' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/components/MouseSelection' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/components/PdfHighlighter' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/components/PdfLoader' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/components/Popup' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/components/Tip' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/components/TipContainer' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/lib/coordinates' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/lib/get-area-as-png' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/lib/get-bounding-rect' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/lib/get-client-rects' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/lib/optimize-client-rects' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/lib/pdfjs-dom' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/build/types' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/components/AreaHighlight' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/components/ContextMenu' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/components/Highlight' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/components/MouseMonitor' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/components/MouseSelection' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/components/PdfHighlighter' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/components/PdfLoader' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/components/Popup' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/components/Tip' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/components/TipContainer' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/lib/coordinates' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/lib/get-area-as-png' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/lib/get-bounding-rect' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/lib/get-client-rects' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/lib/optimize-client-rects' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/lib/pdfjs-dom' {
  declare module.exports: any;
}

declare module '@jagatmachines/react-pdf-highlighter/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jagatmachines/react-pdf-highlighter/build/components/AreaHighlight.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/components/AreaHighlight'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/components/ContextMenu.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/components/ContextMenu'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/components/Highlight.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/components/Highlight'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/components/MouseMonitor.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/components/MouseMonitor'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/components/MouseSelection.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/components/MouseSelection'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/components/PdfHighlighter.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/components/PdfHighlighter'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/components/PdfLoader.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/components/PdfLoader'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/components/Popup.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/components/Popup'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/components/Tip.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/components/Tip'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/components/TipContainer.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/components/TipContainer'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/index' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/index.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/lib/coordinates.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/lib/coordinates'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/lib/get-area-as-png.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/lib/get-area-as-png'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/lib/get-bounding-rect.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/lib/get-bounding-rect'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/lib/get-client-rects.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/lib/get-client-rects'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/lib/optimize-client-rects.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/lib/optimize-client-rects'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/lib/pdfjs-dom.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/lib/pdfjs-dom'>;
}
declare module '@jagatmachines/react-pdf-highlighter/build/types.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/build/types'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/components/AreaHighlight.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/components/AreaHighlight'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/components/ContextMenu.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/components/ContextMenu'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/components/Highlight.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/components/Highlight'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/components/MouseMonitor.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/components/MouseMonitor'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/components/MouseSelection.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/components/MouseSelection'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/components/PdfHighlighter.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/components/PdfHighlighter'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/components/PdfLoader.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/components/PdfLoader'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/components/Popup.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/components/Popup'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/components/Tip.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/components/Tip'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/components/TipContainer.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/components/TipContainer'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/index' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/index.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/lib/coordinates.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/lib/coordinates'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/lib/get-area-as-png.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/lib/get-area-as-png'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/lib/get-bounding-rect.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/lib/get-bounding-rect'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/lib/get-client-rects.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/lib/get-client-rects'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/lib/optimize-client-rects.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/lib/optimize-client-rects'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/lib/pdfjs-dom.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/lib/pdfjs-dom'>;
}
declare module '@jagatmachines/react-pdf-highlighter/src/types.js' {
  declare module.exports: $Exports<'@jagatmachines/react-pdf-highlighter/src/types'>;
}
